# Programa Ingenias+ Data Science

## Entrega notebook 5 - Urdangarin

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [2]:
# Importamos la biblioteca Numpy
import numpy as np

### _Ejercicio N°1_ - Crear un arreglo de ceros de longitud 12

In [6]:
Zo = np.zeros(12) #Creo un vector de ceros de longitud 12
print (Zo)
len (Zo)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


12

### _Ejercicio N°2_ - Crear un arreglo de ceros de longitud 10 y un 10 en la posicion número 5

In [10]:
z1 = np.zeros(10) #Creo un vector de ceros de longitud 10
z1[5] = 10 #Propongo un nuevo valor para la ubicacion 5
print(z1)
len (z1)

[ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.]


10

### _Ejercicio N°3_ - Crear un arreglo que tenga los números del 10 al 49

In [16]:
z2 = np.arange(10,50,1) #Devuelve numero simetricamente distribuidos segun los valores dados.
print(z2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### _Ejercicio N°4_  -Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8

In [26]:
z3 =np.array([[0,1,2],
             [3,4,5],
             [6,7,8]]) #Esta es la forma tradicional pero no me gusta, hay que hacerlo mejor
#print(z3.shape)
z4 = np.arange(9).reshape(3,3)
print(z4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### _Ejercicio N°5_ - Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza

In [52]:
z5 = np.random.randint(0,1000,100)
print (z5)
z6 = np.mean(z5) #Funcion que calcula la media
print(z6)
z7 = np.var(z5) #Funcion que calcula la varianza
print(z7)

[860 618 323 290 283 760  76 858 908 557 829 974 221 762 662   6 764  31
 173 402 524 289 485 344  37  19 989 309 307 442 356  63 354 280 854  12
  86 693 930 192 691 546 147 532 209 160 121 823  17 881 987 806 147 915
 123 214 895 700 888 965  33 749 418  70 388 887 318 910 157 149 394  53
 715  53 544 346 796 511 856 161 117 279  48 907 113 315 756 476 595 763
 509 213 672 303  88 862 118 330 445 800]
459.06
96712.29639999996


### _Ejercicio N°6_ - Calcular la media de un arreglo usando np.sum

In [53]:
le = z5.size
Asum = (np.sum(z5)/[le])
print(Asum)

[459.06]


### _Ejercicio N°7_ - Calcular la varianza de un arreglo usando np.sum y np.mean

In [57]:
res = ((z5)- (np.mean(z5))) #Resta entre el valor del arreglo y la media
Asum = np.sum(res**2) #Sumo esa resta al cuadrado
Avar = (Asum)/z5.size #Divido para la cantidad de elementos
print(Avar)

96712.29639999996


### _Ejercicio N°8_ - Crear un array de números aleatorios usando np.random.randn.

In [59]:
rand = np.random.randint(0,20,100)
print(rand)

[ 2  5 15  3 10 12 12  8 19  6 19 15 12 18 15  6  7  4  0  2 19 14 19  6
 16  1  0 16  2 11 14 13 19 11 14 19 11  9  5  5 12 16  4  8 11  7  7  5
  9 12 19  9 10 17  7 15  0 16  3 19 15 11  5  0  7 13  5 13 14 18  4  4
  2  2  5  8 12 14 16 10  4  2 10 14  4  4  8  2 18  8  2  6 11  3  8  5
 16 11 10  5]
